### PR TITLE
making canvas optional

### PR DESCRIPTION
**Pull request by cesine**
canvas is not installable unless you have a
linux/mac machine with cairo, which is a non-trivial task

### CODE REVIEW

**Comment by JSteunou** [comment]
Moreover, canvas is not needed if you're using CJS syntax from browser (webpack, browserify, ...)
In that case index.js should be rewrite and the lib should be UMD, not using globals.

**Comment by mathisonian** [comment]
+1 for this -- will make the library play nicer with modern node/js workflow

**Comment by mathisonian** [comment]
One thing that may be useful is to include a `postinstall` script that checks whether or not `canvas` installs and may print a message noting that it won't work server side without that dependency

**Comment by cesine** [comment]
@mathisonian  cool :) i agree. i tried to keep the note as brief as possible. 

in other news `npm install` for d3-cloud works using node 4.0! cool! (especially given the canvas -> imagemagick dependancy..)

There is a problem looks like this:

```bash
$ npm run postinstall

> d3.layout.cloud@1.1.2 postinstall /Users/gina/ilanguagehome/d3-cloud
> [ -d  node_modules/canvas ] && echo "Canvas is installed. " || echo "NOTE: Canvas it is not currently installed, if you need server side render you need to install it and its dependancies." #CHECKING FOR CANVAS

NOTE: Canvas it is not currently installed, if you need server side render you need to install it and its dependancies.
```


All is well looks like this:

```bash
$ npm run postinstall

> d3.layout.cloud@1.1.2 postinstall ~/d3-cloud
> [ -d  node_modules/canvas ] && echo "Installed. " || echo "NOTE: Canvas it is not currently installed, if you need server side render you need to install it and its dependancies." #CHECKING FOR CANVAS

Installed.
```

**Comment by mathisonian** [comment]
@cesine awesome that note looks perfect. I just submitted #76 that moves the `require('canvas')` statement into a conditional so client side users should have a breezy time if both of these are merged (I was also running into some `Cannot find module '../build/Release/canvas'` errors during browserify)

**Comment by JSteunou** [comment]
For the browser side, using browserify or webpack for example, another solution would be to add a `browser` entry in the package.json along side the `main`, to provide an UMD version without that `canvas` require statement.

Yep, those builder look up for `browser` before `main`. This allow to be full CJS, but provide a browser version without node stuff.
